# This file is regenerated by .github/workflows/release.yml on every release.
# Edits made by hand will be overwritten — change the workflow instead.
class Ccmon < Formula
  desc "List running Claude Code agents & subagents, open a viewer in a new terminal tab"
  homepage "https://github.com/adamclark64/ccmon"
  version "0.1.0"
  license "MIT"

  depends_on "jq"
  depends_on "tmux"

  on_macos do
    on_arm do
      url "https://github.com/adamclark64/ccmon/releases/download/v0.1.0/ccmon-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/adamclark64/ccmon/releases/download/v0.1.0/ccmon-0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/adamclark64/ccmon/releases/download/v0.1.0/ccmon-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/adamclark64/ccmon/releases/download/v0.1.0/ccmon-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "ccmon"
  end

  test do
    system bin/"ccmon", "--list"
  end
end
